### ISSUE TITLE
Device address offset in PDU incorrect?

### ISSUE THREAD

**Issue by electronut** [NordicSemiconductor/solar_sensor_beacon#2]
sensor_beacon.c defines:

`#define BD_ADDR_OFFS                (3) `

But here's a typical BLE adv packet (via `hcidump`):

```
> 04 3E 2B 02 01 02 01 **76 1E 3C BB 18 FE** 1F 03 19 00 00 02 01
  04 02 0A FC 0D FF FF FF A1 A2 A3 A4 A5 A6 A7 A8 A9 B1 06 08
  62 6C 75 65 79 E4
```

The address offset above is 7.

Also, what does ```p_beacon_pdu[0] = 0x42;``` mean? Shouldn't the first byte should be something like:

`HCI Packet Type: HCI Event (0x04)
`

Please clarify.

**Comment by hanselfberg** [comment]
The HCI event is of a different format than the PDU. More information about the advertising PDUs can be found in the Bluetooth spec, and that format is very close to what the NRF_RADIO peripheral is using as well [NRF_RADIO peripheral documentation](http://infocenter.nordicsemi.com/index.jsp?topic=%2Fcom.nordic.infocenter.nrf52840.ps%2Fradio.html&cp=2_1_0_21&anchor=concept_lhd_ygj_4r).

0x42 is the packet type for non-connectable advertising OR:ed together with the TxAddr bit.

**Comment by EarthLord** [comment]
@hanselfberg  If you see in the Bluetooth Spec Vol 6, Part B, section 2.3, the Advertisement protocol data unit (PDU) consists of 2 octets of header and the rest as payload. Since the BLE MAC address is the 6 octets following the header, the define BD_ADDR_OFFS should be 2. This would also mean that the m_beacon_pdu_init function should be

```
static void m_beacon_pdu_init(uint8_t * p_beacon_pdu)
{
    p_beacon_pdu[0] = 0x42;
    p_beacon_pdu[1] = 0;
#if 0
    Only two octets for header of a PDU
    p_beacon_pdu[2] = 0;
#endif
}
```

**Comment by hanselfberg** [comment]
The reason why it is 3 instead of 2 is because the way the radio is configured. See hal_radio.c at this part of the code:
```
    NRF_RADIO->PCNF0 = (((1UL) << RADIO_PCNF0_S0LEN_Pos) & RADIO_PCNF0_S0LEN_Msk)
                     | (((2UL) << RADIO_PCNF0_S1LEN_Pos) & RADIO_PCNF0_S1LEN_Msk)
                     | (((6UL) << RADIO_PCNF0_LFLEN_Pos) & RADIO_PCNF0_LFLEN_Msk);
```
The S0 length is one byte, and exactly maps to p_beacon_pdu[0]. The length field is 6 bits, and uses 6 bits of p_beacon_pdu[1]. S1 field is 2 bits and uses 2 bits of p_beacon_pdu[2]. This means the PDU header takes 3 bytes in RAM, but only 2 bytes on air.

However, for this particular application it would also be possible to set the length field size to 8 and the S1 size to 0 to save one byte of RAM. Then the BD_ADDR_OFFS would be 2 instead of 3.

**Comment by EarthLord** [comment]
Ok, thanks for the clarification!
